### ISSUE TITLE
wx module missing

### ISSUE THREAD

**Issue by rahulkashyap1506** [dr-nyt/Translated-Novel-Downloader#14]
whenever I try to start main.py or any other files, it says 
"ModuleNotFoundError: No module named 'wx'"

**Comment by webdagger** [comment]
If you are not using the .exe for windows, you'll need to install the dependencies included in the requirments.txt file. 
I will close this when I have verified there is a requirements file present.
But you can get started by installing them manually 

> pip install wxpython cfscrape beautifulsoup4 ebooklib

**Comment by dr-nyt** [comment]
Oh, thanks for pointing this out, I'll add the pre-requirements for manually compiling the app. For now you can easily fix it with @webdagger's suggestion above; by typing the following in your cmd:
` pip install wxpython cfscrape beautifulsoup4 ebooklib`

You can also join our discord group where we actively answer general questions: https://discord.gg/Wya4Dst

Kind Regards,
dr_nyt.

**Comment by dr-nyt** [comment]
I've added a [readme file](https://github.com/dr-nyt/Translated-Novel-Downloader/tree/master/Version%200.8) to the Version 0.8 folder and should provide a further insight on the project settings. It is still incomplete as I will further explain the main logic of how the code works, but it does answer your issue.

**Comment by dr-nyt** [comment]
I just had someone ask me how to run the app for just using it. If your intention is to just use the app normally and not make customizations to the code then I'd suggest simply running the .exe file we have provided following the steps here: https://github.com/dr-nyt/Translated-Novel-Downloader/blob/master/README.md

This should have answered your question. I'll close this issue now, but if you still are having issues then you can reopen this issue or directly ask us on our discord.

Kind Regards,
dr_nyt.
