### ISSUE TITLE
[Bug Report] Beta feedback

### ISSUE THREAD

**Issue by Jade-mist** [dr-nyt/Translated-Novel-Downloader#15]
Beta Version 0.9

- When you enter an invalid volume number the "Run" button turns gray and you can't click it, even if you change the number to a valid one.
And you have to restart the program.

-  The footnotes are not working, whereas in version 0.7.3 they are
![image](https://user-images.githubusercontent.com/50962756/59959580-388fea00-94c3-11e9-8ea4-f30612aeb748.png)
This is version 0.7.3

![image](https://user-images.githubusercontent.com/50962756/59959586-49d8f680-94c3-11e9-8c65-31e96cf6774e.png)
This is the Beta.

You can click the blue number in 0.7.3 and it takes you directly to the footnote at the end of the chapter.

- The spacing between the paragraphs is rather large, but this was also "fixed" in previous versions, although this is a matter of preference.

- When I enter a valid URL and add a few random things at the end to make it an invalid URL, the "Run" button turns gray, there is no error, nothing happens and you have to restart the program.
![image](https://user-images.githubusercontent.com/50962756/59959596-742ab400-94c3-11e9-829e-639f88b7699f.png)

Thank you.

**Comment by dr-nyt** [comment]
All of the mentioned issues have been addressed! Expect a new version in the coming month :D
