### ISSUE TITLE
[Bug Report]: Consecutive Downloads

### ISSUE THREAD

**Issue by Rebranding** [dr-nyt/Translated-Novel-Downloader#16]
**Please complete the following information):**
 - Operating System [OS]: Windows 8.1 Current Build as of 7/6/19
 - App Version: Version 0.8

**Describe the bug**
Can't make a second epub file consecutively. It attempted to add the new data to the previous file, and only failed at the end.

I will note that just closing and reopening the program fixes the problem entirely, but I thought you might want to know for development reasons.

**To Reproduce**
1. Go to open the main python program.
2. Run the program on NovelPlanet for The Legendary Moonlight Sculptor.
3. After it finishes, keep all settings the same and just change the url so that it becomes that of I Alone Level Up (also on NovelPlanet, to be clear).
4. Run the program again.
5. After downloading all the files, the error occurs when it tries to make a directory for the new file, but the new file is really just a copy of the previous file with some new data.

**Expected behavior**
A second epub file to be produced.

**Screenshots**

**Comment by dr-nyt** [comment]
Hey!

Thank you for taking your time bring this issue up. I will look into this issue and get back to you as soon as possible.

**Comment by dr-nyt** [comment]
Your version is now fixed in [Version 0.8.1](https://github.com/dr-nyt/Translated-Novel-Downloader/releases)
I'll close this issue for now, but by any chance if you continue to have the issue then feel free to comment below.
