### ISSUE TITLE
Version 0.7.1 not starting

### ISSUE THREAD

**Issue by Jade-mist** [dr-nyt/Translated-Novel-Downloader#7]
Hey,
I tried using the newest version 0.7.1. I downloaded the .zip file and extracted it, but when I tried running WuxiaScraper.exe it doesn't start. It just sits in the Task Manager in the background and does nothing.

**Comment by dr-nyt** [comment]
It seems to be working fine on my end. Please make sure that the rsc/ folder is in the same directory as NovelScraper.exe and all the contents are inside (Icon.ico and Novel Cover.png)

**Comment by dr-nyt** [comment]
I tried running out on a different machine with no python and still works. Here are the steps I followed.
1. Unzip the contents of the zip file into a folder
![](https://user-images.githubusercontent.com/41040912/58767035-fac03580-8596-11e9-9c1c-8c38cf72db7d.jpg)
2. Run the NovelScraper.exe [If you have an AntiVirus then it will scan it and should have no problems.]
    - Your AntiVirus might be blocking it for some reason, but it's very unlikely. I use Avast for reference.
    - A PC restart may help as well.

**Comment by Jade-mist** [comment]
Every folder is there, I checked and my antivirus is not blocking it as far as I can tell and I restarted my computer. I also tried downloading the pyhton run file and it starts. However, I tried downloading a novel from NovelPlanet and m.wuxiaworld.co and it doesn't work. When downloading a novel from m.wuxiaworld.co it creates an .epub file, but it's emptry exept for the title of the novel I tried downloading. From NovelPlanet it displayes and error : Node.js is missing. Downloading a novel from wuxiaworld.com is still working fine.

**Comment by dr-nyt** [comment]
I'll check the errors, but the .exe itself runs now yes?

**Comment by dr-nyt** [comment]
Note to self: Never release in a rush. I seem to have fixed most of the problems with NovelPlanet and WuxiaWorld. The code WuxiaWorldCo from a collaborator @webdagger and I made a mistake when I made the file to be made into an executable.

I'll revert back to 0.7 for now and re-release it later. Thanks for the heads up :)

**Comment by Jade-mist** [comment]
WuxiaScrapper.exe is still not working for version 0.7.1, I downloaded the .zip file with the python files and I started the "run" pyhton file there. It seems the 0.7 version .exe file is working. Does it have anything to do with pastebin.com by any chance as my antivirus is showing me this: 
![image](https://user-images.githubusercontent.com/50962756/58818118-fc8d0600-8635-11e9-86a6-66e49779ce81.png). And, of course, the .exe file shows "Failed to execute script run". Just asking to know if it is safe. Good luck and thank you!

**Comment by dr-nyt** [comment]
Could you run NovelScraper-0.7.1.exe using the following steps:

1: Type cmd in the directory bar of the folder your .exe file is stored in and hit <enter>
![first](https://user-images.githubusercontent.com/41040912/58818831-d704fa00-863f-11e9-9a20-2516f9225e5e.jpg)

2. Type the name of the file NovelScraper-0.7.1.exe in the cmd and hit <enter>
![second](https://user-images.githubusercontent.com/41040912/58818857-f6038c00-863f-11e9-9c68-7e74f9611740.jpg)

And paste whatever the cmd returns here. Thank you for cooperating :D

**Comment by Jade-mist** [comment]
![image](https://user-images.githubusercontent.com/50962756/58819246-7faf5b80-8638-11e9-8734-3ed4bddc47ae.png)

I don't know if I did it correctly, I tried two different "commands", since the file name in my folder is "NovelScraper".

**Comment by dr-nyt** [comment]
Try NovelScraper.exe

**Comment by Jade-mist** [comment]
![image](https://user-images.githubusercontent.com/50962756/58819656-5fcc6780-8639-11e9-9bc4-d080c463e152.png)

I should add that a minute ago, a few minutes after I executed the last "commands", the file opened and displayed the error "Failed to execute script run" (I am guessing this is because I still have not added pastebin.com to exclusions in my antivirus?).

**Comment by Jade-mist** [comment]
Yep, it started again.

**Comment by dr-nyt** [comment]
Hmm, I'm not sure why it blocks Pastebin, maybe it has something to do with Pastebin being the place where most of the username and password dumps happen but still.

I write the version number of the app on Pastebin and when the app runs, it compares the version number on Pastebin and the one stored in its file and tells the user if they have to update or not.
 
Concerning the problem with wuxiaworld.co, it seems to be a problem with the code I got from @webdagger and not on my part, as his original code has also stopped working all of a sudden.

Thanks for bringing up the issue though, it helped fix a lot of problems. Please have this badge of honor from my part 🥇

**Comment by Jade-mist** [comment]
Thank you, I really appreciate you are continuing to work on this project and actively trying to make a better product. I am also very happy there are other people who are contributing, wuxiaworld.co has a huge database and some unique novels I can't find anywhere else, so it is a great edition. Keep up the good work.

**Comment by dr-nyt** [comment]
I removed support for wuxiaworld.co from 0.7.1 and re-released it. I've done this to avoid any confusion. You can expect wuxiaworld.co support in 0.7.2.

I'll close this issue for now unless you find anymore bugs :) Oh and @webdagger added support for wuxiaworld.co so you can check out his fork on my project if you are interested.

**Comment by webdagger** [comment]
I have the same issue on windows with the exe file.  I can't get it to run and I don't have an antivirus. 
@dr-nyt, The wuxiaco class does not work?  I read an issue where it is generating only a blank novel.

**Comment by dr-nyt** [comment]
@Jade-mist what did you exactly do to fix your .exe not working problem? For some reason, it works fine on all my devices.

And @webdagger I just figured out the problem. I have been using wuxiaworld.co for getting the novel links but the actual website is m.wuxiaworld.co. I got confused between the two, my bad ;3

**Comment by dr-nyt** [comment]
I'll add a command which checks the starting of a link and lets the user know if its the wrong website.

**Comment by webdagger** [comment]
@dr-nyt I see, on OSX , I notice if I can't connect to the I hereby  the app does not lunch. I'll try and see if that's the same issue for the windows. Can we do better error handling ?  
I see the alpha build for Android, are you using java ? 
We should probably get a slack channel

**Comment by Jade-mist** [comment]
To run it, I followed the steps you described above, using cmd. It takes around 4 minutes for the .exe to start.

**Comment by dr-nyt** [comment]
@Jade-mist is your computer slow? I have a very high end computer so I see almost 0 delay in opening the app. Running it on my slow laptop had the same results aswell. I'm very confused as to why it would take so long to run.

@webdagger yes we should probably work on better error handling. As for the android build, I haven't really started anything and was initially thinking of some how integrating python into an apk. Maybe we should directly move to java at this point. And what do you mean by a slack channel?

**Comment by dr-nyt** [comment]
@Jade-mist is it slow only when running the 0.7.1.exe or the previous release aswell?

**Comment by Jade-mist** [comment]
I am not sure it is slow, I would consider it a mid to high end computer, every other program opens almost immediately. I could get you my computer specifications. 

Only version 0.7.1, version 0.7 starts almost immediately.

**Comment by webdagger** [comment]
@dr-nyt https://play.google.com/store/apps/details?id=com.Slack
I can't get it to run on my windows. And I don't think it's antivirus. The scripts work fine. Just not the executable

**Comment by dr-nyt** [comment]
@Jade-mist that does give me a few hints. I'll try to see what the issue is and I'll tag you here when a new build is ready :D 

@webdagger I'll download it now and check it out

**Comment by webdagger** [comment]
@jade-mist it shouldn't even take about 4 mins to start, the app isn't that large. 
@dr-nyt, I will work on my fork, perhaps write the GUI in wxpython(I'm don't speak Tinkter fluently). One downside I see is the dependence on the python install of the user. Perhaps the executable should be standalone

**Comment by dr-nyt** [comment]
@webdagger I removed the code for dependencies install in the executable and put all the code into a single run.py 
https://github.com/dr-nyt/Translated-Novel-Downloader/blob/master/Version%200.7.1/Executable%20Build/run.py

**Comment by dr-nyt** [comment]
@webdagger could I have your email address to add you to slacks.

**Comment by webdagger** [comment]
ayomipoe@gmail.com

**Comment by dr-nyt** [comment]
@webdagger it says the email bounced... I'm not sure if that means you got the request or not.

**Comment by webdagger** [comment]
I created a workspace, can I have your email address?

**Comment by dr-nyt** [comment]
alright, autumnwind101011@gmail.com

**Comment by webdagger** [comment]
Sent the invite

**Comment by dr-nyt** [comment]
@Jade-mist I made a few changes, could you try running this: (ignore the update msg that might popup)
[Version-0.7.2.zip](https://github.com/dr-nyt/Translated-Novel-Downloader/files/3254134/Version-0.7.2.zip)

**Comment by dr-nyt** [comment]
Nvm, I officially released 0.7.2. Hopefully, that fixes the problem. @webdagger said his startup time was reduced to about 12 seconds. 

Also by any chance is your OS 32-bit?

**Comment by Jade-mist** [comment]
Version 0.7.2 starts after a second or two and there is no warning from my antivirus. My system is 64-bit.
As these problems are now resolved I will close the issue. Thank you for fixing them!
